[package]
name = "cached-nix-shell"
version = "0.1.6"
authors = ["Albert Safin <xzfcpw@gmail.com>"]
license = "Unlicense OR MIT"
edition = "2018"

[build-dependencies]
which = "6.0.1"

[dependencies]
blake3 = "1.5.1"
bytelines = { version = "2.5.0", default-features = false }
itertools = "0.13.0"
microjson = "0.1.6"
rustix = { version = "0.38.34", features = ["fs"], default-features = false }
tempfile = "3.10.1"
ufcs = "0.1.0"
